import React, {useEffect, useRef, useState} from 'react'
import {createRoot} from 'react-dom/client'
import {BrowserRouter, Link, NavLink, Route, Routes, useParams} from 'react-router-dom'
import './styles.css'
const cats=['all','world','business','technology','science','culture','sports']
const pretty = v => v === 'all' ? 'All stories' : v[0].toUpperCase()+v.slice(1)
const age = d => { const h=Math.max(1,Math.round((Date.now()-new Date(d))/36e5)); return h<24?`${h}h ago`:new Date(d).toLocaleDateString('en-US',{month:'short',day:'numeric'}) }
const youtubePreview = url => { const id = url?.match(/[?&]v=([^&]+)/i)?.[1] || url?.match(/youtu\.be\/([^?&/]+)/i)?.[1]; return id ? `https://i.ytimg.com/vi/${id}/hqdefault.jpg` : '' }
const previewFor = article => article.image || (article.video?.provider === 'youtube' ? youtubePreview(article.video.url) : '')
function Header(){return <><header><Link className="wordmark" to="/">THE DAILY<br/><i>LEDGER</i></Link><nav><NavLink to="/feed">Latest</NavLink><a href="#edition">The Edition</a><a href="#about">About</a></nav><div className="header-actions"><span className="search">⌕</span><Link className="subscribe" to="/feed">Read the news <b>→</b></Link></div></header><div className="rule"/></>}
function VideoBadge({video}){return video&&<span className="video-badge"><b>▶</b> Video</span>}
function Media({article, feature=false}){const preview=previewFor(article);const [hasImage,setHasImage]=useState(Boolean(preview)); if(article.video?.type==='direct')return <div className="image-wrap video-wrap"><video src={article.video.url} poster={preview} muted autoPlay loop playsInline controls={!feature}/><span className="category">{article.category}</span><VideoBadge video={article.video}/></div>; if(hasImage)return <div className="image-wrap"><img src={preview} alt="" onError={()=>setHasImage(false)}/><span className="category">{article.category}</span><VideoBadge video={article.video}/>{article.video?.type==='external'&&<span className="play-button">▶</span>}</div>; return article.video?.type==='external'&&<div className="image-wrap no-image"><span className="category">{article.category}</span><VideoBadge video={article.video}/><span className="play-button">▶</span></div>}
function Card({article, feature=false}){const isExternalVideo=article.video?.type==='external'; const copy=<><Media article={article} feature={feature}/><div className="card-copy"><p className="meta">{article.source} <em>·</em> {age(article.publishedAt)}</p><h2>{article.title}</h2><p className="dek">{article.description}</p><span className="read">{article.video?'Watch story':'Read story'} <b>→</b></span></div></>; return <article className={feature?'card feature':'card'}>{isExternalVideo?<a href={article.url} target="_blank" rel="noreferrer">{copy}</a>:<Link to={`/article/${article.id}`}>{copy}</Link>}</article>}
function useArticles(category='all'){const [articles,setArticles]=useState([]),[page,setPage]=useState(1),[loading,setLoading]=useState(true); useEffect(()=>{setLoading(true);setPage(1);fetch(`/api/articles?category=${category}`).then(r=>r.json()).then(d=>setArticles(d)).finally(()=>setLoading(false))},[category]); const more=()=>{if(loading)return; setLoading(true); const next=page+1;fetch(`/api/articles?page=${next}&category=${category}`).then(r=>r.json()).then(d=>{setArticles(x=>[...x,...d]);setPage(next)}).finally(()=>setLoading(false))};return{articles,loading,more}}
function Landing(){const {articles,loading}=useArticles(); if(loading)return <main className="loading">Loading today’s edition…</main>; const [lead,...rest]=articles; const videos=articles.filter(a=>a.video).slice(0,2);return <><main><section className="edition"><p>Friday, July 17, 2026 <span>•</span> Independent reporting for a changing world</p><h1>The stories<br/>that <i>shape</i> us.</h1><Link to="/feed" className="text-link">Explore today’s edition <b>→</b></Link></section><section className="lead-grid"><Card article={lead} feature/><aside className="briefing"><p className="eyebrow">THE MORNING BRIEFING</p><h2>The world, in<br/><i>clearer focus.</i></h2><p>Essential reporting and compelling ideas, selected for the curious reader.</p><Link to="/feed" className="text-link">Start reading <b>→</b></Link><div className="issue">No. 07 <span>—</span> 2026</div></aside></section>{videos.length>0&&<section className="video-rail"><div><p className="eyebrow">WATCH THE FEED</p><h2>Video from trusted newsrooms and social desks</h2><p>Muted autoplay is used for direct video feeds. X/Twitter items show a thumbnail and play cue, then open the source for viewing.</p></div><div className="video-list">{videos.map(a=><Card key={a.id} article={a}/>)}</div></section>}<section className="section-title"><div><p className="eyebrow">FROM THE NEWSROOM</p><h2>What we’re following</h2></div><Link to="/feed" className="text-link">View all stories <b>→</b></Link></section><section className="grid">{rest.slice(0,3).map(a=><Card key={a.id} article={a}/>)}</section></main><Footer/></>}
function Feed(){const [category,setCategory]=useState('all');const {articles,loading,more}=useArticles(category);const sentinel=useRef();useEffect(()=>{const o=new IntersectionObserver(([e])=>e.isIntersecting&&articles.length&&more(),{rootMargin:'300px'});if(sentinel.current)o.observe(sentinel.current);return()=>o.disconnect()},[articles]);return <main className="feed"><div className="feed-title"><p className="eyebrow">THE DAILY LEDGER</p><h1>Latest stories</h1><p>A living index of the ideas and events shaping our day.</p></div><div className="filters">{cats.map(c=><button onClick={()=>setCategory(c)} className={category===c?'active':''} key={c}>{pretty(c)}</button>)}</div><section className="feed-grid">{articles.map(a=><Card key={a.id} article={a}/>)}</section><div ref={sentinel} className="load">{loading?'Gathering more stories…':articles.length?'Keep scrolling for more':'You’re all caught up.'}</div></main>}
function Article(){const {id}=useParams();const [article,setArticle]=useState();const [hasImage,setHasImage]=useState(true);useEffect(()=>{setArticle();setHasImage(true);fetch(`/api/articles/${id}`).then(r=>r.json()).then(setArticle)},[id]);if(!article)return <main className="loading">Opening story…</main>;const preview=previewFor(article);return <main className="article"><Link to="/feed" className="back">← Back to latest stories</Link><p className="eyebrow accent">{article.category}</p><h1>{article.title}</h1><p className="standfirst">{article.description}</p><div className="byline"><span>By {article.source}</span><span>{new Date(article.publishedAt).toLocaleDateString('en-US',{month:'long',day:'numeric',year:'numeric'})}</span><span>· {age(article.publishedAt)}</span></div>{article.video?.type==='direct'?<video className="hero" src={article.video.url} poster={preview} muted autoPlay playsInline controls/>:hasImage&&preview&&<div className="article-media"><img className="hero" src={preview} alt="" onError={()=>setHasImage(false)}/>{article.video&&<span className="play-button">▶</span>}</div>}<div className="story"><p>{article.content}</p><p>Thoughtful reporting starts with a closer look. The Daily Ledger gathers the essential context around the world’s most important conversations, then gives readers a clear path to the original journalism.</p><a href={article.url} target="_blank" rel="noreferrer" className="source-link">{article.video?'Watch at the original source':'Read the original report'} <b>↗</b></a></div></main>}
function Footer(){return <footer><span className="wordmark">THE DAILY<br/><i>LEDGER</i></span><p>Thoughtful journalism for the curious citizen.</p><span>© 2026 The Daily Ledger</span></footer>}
function App(){return <BrowserRouter><Header/><Routes><Route path="/" element={<Landing/>}/><Route path="/feed" element={<Feed/>}/><Route path="/article/:id" element={<Article/>}/><Route path="*" element={<Landing/>}/></Routes></BrowserRouter>}
createRoot(document.getElementById('root')).render(<App/>)
