import React, {useEffect, useRef, useState} from 'react'
import {createRoot} from 'react-dom/client'
import {BrowserRouter, Link, NavLink, Route, Routes, useParams} from 'react-router-dom'
import './styles.css'
const cats=['all','world','business','technology','science','culture','sports']
const pretty = v => v === 'all' ? 'All stories' : v[0].toUpperCase()+v.slice(1)
const age = d => { const h=Math.max(1,Math.round((Date.now()-new Date(d))/36e5)); return h<24?`${h}h ago`:new Date(d).toLocaleDateString('en-US',{month:'short',day:'numeric'}) }
function SourceLogo({article}){const [showLogo,setShowLogo]=useState(Boolean(article.sourceLogo));return <span className="source">{showLogo&&<img className="source-logo" src={article.sourceLogo} alt={`${article.source} logo`} onError={()=>setShowLogo(false)}/>}<span className={showLogo?'source-name visually-hidden':'source-name'}>{article.source}</span></span>}
const commentDate = d => new Date(d).toLocaleString('en-US',{month:'short',day:'numeric',year:'numeric',hour:'numeric',minute:'2-digit'})
function Header(){return <><header><Link className="wordmark" to="/">THE DAILY<br/><i>LEDGER</i></Link><nav><NavLink to="/feed">Latest</NavLink><a href="#edition">The Edition</a><a href="#about">About</a></nav><div className="header-actions"><span className="search">⌕</span><Link className="subscribe" to="/feed">Read the news <b>→</b></Link></div></header><div className="rule"/></>}
function Card({article, feature=false}){const [hasImage,setHasImage]=useState(Boolean(article.image));return <article className={feature?'card feature':'card'}><Link to={`/article/${article.id}`}>{hasImage&&<div className="image-wrap"><img src={article.image} alt="" onError={()=>setHasImage(false)}/><span className="category">{article.category}</span></div>}<div className="card-copy"><p className="meta"><SourceLogo article={article}/> <em>·</em> {age(article.publishedAt)}</p><h2>{article.title}</h2><p className="dek">{article.description}</p><span className="read">Read story <b>→</b></span></div></Link></article>}
function useArticles(category='all'){const [articles,setArticles]=useState([]),[page,setPage]=useState(1),[loading,setLoading]=useState(true); useEffect(()=>{setLoading(true);setPage(1);fetch(`/api/articles?category=${category}`).then(r=>r.json()).then(d=>setArticles(d)).finally(()=>setLoading(false))},[category]); const more=()=>{if(loading)return; setLoading(true); const next=page+1;fetch(`/api/articles?page=${next}&category=${category}`).then(r=>r.json()).then(d=>{setArticles(x=>[...x,...d]);setPage(next)}).finally(()=>setLoading(false))};return{articles,loading,more}}
function Landing(){const {articles,loading}=useArticles(); if(loading)return <main className="loading">Loading today’s edition…</main>; const [lead,...rest]=articles;return <><main><section className="edition"><p>Friday, July 17, 2026 <span>•</span> Independent reporting for a changing world</p><h1>The stories<br/>that <i>shape</i> us.</h1><Link to="/feed" className="text-link">Explore today’s edition <b>→</b></Link></section><section className="lead-grid"><Card article={lead} feature/><aside className="briefing"><p className="eyebrow">THE MORNING BRIEFING</p><h2>The world, in<br/><i>clearer focus.</i></h2><p>Essential reporting and compelling ideas, selected for the curious reader.</p><Link to="/feed" className="text-link">Start reading <b>→</b></Link><div className="issue">No. 07 <span>—</span> 2026</div></aside></section><section className="section-title"><div><p className="eyebrow">FROM THE NEWSROOM</p><h2>What we’re following</h2></div><Link to="/feed" className="text-link">View all stories <b>→</b></Link></section><section className="grid">{rest.slice(0,3).map(a=><Card key={a.id} article={a}/>)}</section></main><Footer/></>}
function Feed(){const [category,setCategory]=useState('all');const {articles,loading,more}=useArticles(category);const sentinel=useRef();useEffect(()=>{const o=new IntersectionObserver(([e])=>e.isIntersecting&&articles.length&&more(),{rootMargin:'300px'});if(sentinel.current)o.observe(sentinel.current);return()=>o.disconnect()},[articles]);return <main className="feed"><div className="feed-title"><p className="eyebrow">THE DAILY LEDGER</p><h1>Latest stories</h1><p>A living index of the ideas and events shaping our day.</p></div><div className="filters">{cats.map(c=><button onClick={()=>setCategory(c)} className={category===c?'active':''} key={c}>{pretty(c)}</button>)}</div><section className="feed-grid">{articles.map(a=><Card key={a.id} article={a}/>)}</section><div ref={sentinel} className="load">{loading?'Gathering more stories…':articles.length?'Keep scrolling for more':'You’re all caught up.'}</div></main>}
function Comments({articleId}){const [comments,setComments]=useState([]),[name,setName]=useState(''),[body,setBody]=useState(''),[status,setStatus]=useState(''),[loading,setLoading]=useState(true),[posting,setPosting]=useState(false),[liking,setLiking]=useState({});useEffect(()=>{setLoading(true);setStatus('');setLiking({});fetch(`/api/articles/${articleId}/comments`).then(r=>r.json()).then(d=>{if(Array.isArray(d))setComments(d.map(c=>({...c,likes:Number(c.likes)||0})));}).catch(()=>setStatus('Comments are unavailable right now.')).finally(()=>setLoading(false))},[articleId]);const submit=e=>{e.preventDefault();if(posting)return;setPosting(true);setStatus('');fetch(`/api/articles/${articleId}/comments`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({name,body})}).then(async r=>{const d=await r.json();if(!r.ok)throw new Error(d.error||'Unable to post your comment.');setComments(x=>[{...d,likes:Number(d.likes)||0},...x]);setBody('');setStatus('Thanks for adding your perspective.')}).catch(err=>setStatus(err.message)).finally(()=>setPosting(false))};const likeComment=id=>{if(liking[id])return;setLiking(x=>({...x,[id]:true}));setStatus('');fetch(`/api/articles/${articleId}/comments/${id}/like`,{method:'POST'}).then(async r=>{const d=await r.json();if(!r.ok)throw new Error(d.error||'Unable to like this comment.');setComments(x=>x.map(c=>c.id===id?{...c,likes:Number(d.likes)||0}:c))}).catch(err=>setStatus(err.message)).finally(()=>setLiking(x=>{const next={...x};delete next[id];return next}))};return <section className="comments"><div className="comments-heading"><p className="eyebrow">Reader discussion</p><h2>Join the conversation</h2><p>No account required. Share your thoughts with other Daily Ledger readers.</p></div><form className="comment-form" onSubmit={submit}><label>Your name <span>(optional)</span><input value={name} onChange={e=>setName(e.target.value)} maxLength="80" placeholder="Anonymous reader"/></label><label>Comment<textarea value={body} onChange={e=>setBody(e.target.value)} maxLength="1000" placeholder="What stood out to you?" required/></label><div className="comment-actions"><span>{body.length}/1000</span><button disabled={posting}>{posting?'Posting…':'Post comment'}</button></div>{status&&<p className="comment-status">{status}</p>}</form><div className="comment-list">{loading?<p className="empty-comments">Loading comments…</p>:comments.length?comments.map(c=><article className="comment" key={c.id}><div className="comment-head"><strong>{c.name}</strong><time>{commentDate(c.createdAt)}</time></div><p>{c.body}</p><div className="comment-feedback"><button type="button" className="like-button" disabled={Boolean(liking[c.id])} onClick={()=>likeComment(c.id)}>{liking[c.id]?'Liking…':'Like'}</button><span>{Number(c.likes)||0} {(Number(c.likes)||0)===1?'like':'likes'}</span></div></article>):<p className="empty-comments">Be the first reader to comment on this story.</p>}</div></section>}
function Article(){const {id}=useParams();const [article,setArticle]=useState();const [hasImage,setHasImage]=useState(true);useEffect(()=>{setArticle();setHasImage(true);fetch(`/api/articles/${id}`).then(r=>r.json()).then(setArticle)},[id]);if(!article)return <main className="loading">Opening story…</main>;return <main className="article"><Link to="/feed" className="back">← Back to latest stories</Link><p className="eyebrow accent">{article.category}</p><h1>{article.title}</h1><p className="standfirst">{article.description}</p><div className="byline"><span>By {article.source}</span><span>{new Date(article.publishedAt).toLocaleDateString('en-US',{month:'long',day:'numeric',year:'numeric'})}</span><span>· {age(article.publishedAt)}</span></div>{hasImage&&article.image&&<img className="hero" src={article.image} alt="" onError={()=>setHasImage(false)}/>}<div className="story"><p>{article.content}</p><p>Thoughtful reporting starts with a closer look. The Daily Ledger gathers the essential context around the world’s most important conversations, then gives readers a clear path to the original journalism.</p><a href={article.url} target="_blank" rel="noreferrer" className="source-link">Read the original report <b>↗</b></a></div><Comments articleId={id}/></main>}
function Footer(){return <footer><span className="wordmark">THE DAILY<br/><i>LEDGER</i></span><p>Thoughtful journalism for the curious citizen.</p><span>© 2026 The Daily Ledger</span></footer>}
function App(){return <BrowserRouter><Header/><Routes><Route path="/" element={<Landing/>}/><Route path="/feed" element={<Feed/>}/><Route path="/article/:id" element={<Article/>}/><Route path="*" element={<Landing/>}/></Routes></BrowserRouter>}
createRoot(document.getElementById('root')).render(<App/>)
